using BepInEx;
using BepInEx.Logging;
using HarmonyLib;
using TimberbornAPI;

namespace AutomaticBeaverMigration
{
    [BepInPlugin("name.plugin.automaticbeavermigration", "Automatic Beaver Migration", "0.1.0")]
    [BepInDependency("com.timberapi.timberapi")]
    
    public class AutomaticBeaverMigrationPlugin : BaseUnityPlugin
    {
        internal static ManualLogSource Log;
        
        private void Awake()
        {
            // Add static logger for internal mod use
            Log = Logger;

            // Autogenerated first Configurator
            TimberAPI.DependencyRegistry.AddConfigurator(new AutomaticBeaverMigrationConfigurator());
            
            new Harmony("name.plugin.automaticbeavermigration").PatchAll();
        }
    }
    
}
